### ISSUE TITLE
Unable to install mingw64-i686-pkg-config and mingw64-x86_64-pkg-config when pkg-config-1.6.0-1 is installed

### ISSUE THREAD

**Issue by gugavaro** [fdopen/opam-repository-mingw#54]
I am trying to install mingw64-i686-pkg-config, but it fails because installed package pkg-config-1.6.0-1 obsoletes mingw64-x86_64-pkg-config provided by mingw64-x86_64-pkg-config-1.6.0-1

log:

Installing the following packages:                                                                                              
mingw64-x86_64-pkg-config                                                                                                       
By installing you accept licenses for the packages.                                                                             
 [Cygwin] Starting cygwin install, version 2.895                                                                                
 [Cygwin] User has backup/restore rights                                                                                        
 [Cygwin] Current Directory: C:\cygwin64\packages                                                                               
 [Cygwin] Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.      
 [Cygwin] root: C:\cygwin64 system                                                                                              
 [Cygwin] Selected local directory: C:\cygwin64\packages                                                                        
 [Cygwin] net: Preconfig                                                                                                        
 [Cygwin] site: http://mirrors.kernel.org/sourceware/cygwin/                                                                                                   
 [Cygwin] solving: 1 tasks, update: no, use test packages: no                                                                   
 [Cygwin] Problem 1/1                                                                                                           
 [Cygwin] installed package pkg-config-1.6.0-1 obsoletes mingw64-x86_64-pkg-config provided by mingw64-x86_64-pkg-config-1.6.0-1

 [Cygwin] Solution 1/2                                                                                                          
 [Cygwin]   - allow replacement of pkg-config-1.6.0-1 with pkg-config-0.29.1-1                                                  
 [Cygwin] Solution 2/2 (default)                                                                                                
 [Cygwin]   - do not ask to install mingw64-x86_64-pkg-config-1.6.0-1                                                           
 [Cygwin] Augmented Transaction List: is empty                                                                                  
 [Cygwin] Changing gid back to original                                                                                         
 [Cygwin] running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"                                           
 [Cygwin] running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"                                          
 [Cygwin] running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_man-db.sh"                                  
 [Cygwin] Changing gid to Administrators                                                                                        
 [Cygwin] Ending cygwin install

**Comment by fdopen** [comment]
Sorry, https://github.com/fdopen/opam-repository-mingw/commit/8eb6ba60a602787741ba02cc624acd56ee14d073 was probably wrong, but https://github.com/fdopen/opam-repository-mingw/commit/3936082c17a25bdfc836dfb16df3502a23d42a3f should fix it. Try the same command again after `opam update`.

**Comment by gugavaro** [comment]
Still getting errors when I try to install opam packages

```

# Detecting depexts using flags: x86_64 mswindows win32 cygwinports
# The following system packages are needed:
#  - gmp
#  - libffi
#  - pkg-config
#  - sqlite3
#  - system:time
installed:gmp
installed:libffi
installed:sqlite3
installed:system:time
# The following new OS packages need to be installed: pkg-config
Starting cygwin install, version 2.895
User has backup/restore rights
Current Directory: C:\cygwin64\packages
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: C:\cygwin64 system
Selected local directory: C:\cygwin64\packages
net: Preconfig
site: http://cygwin.mirror.constant.com/
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst.sig
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst
solving: 1 tasks, update: no, use test packages: no

Problem 1/1

installed package pkg-config-1.6.0-1 obsoletes mingw64-x86_64-pkg-config provided by mingw64-x86_64-pkg-config-1.6.0-1

Solution 1/2
  - allow replacement of pkg-config-1.6.0-1 with pkg-config-0.29.1-1
Solution 2/2 (default)
  - do not ask to install mingw64-x86_64-pkg-config-1.6.0-1

```

**Comment by fdopen** [comment]
the dependency seems to be hardcoded at several places. What do you try to install? I've now also fixed `ctypes-foreign.0.4.0` (https://github.com/fdopen/opam-repository-mingw/commit/993fa149171a0c1698c97faf2f767042ae8abc93), but it could be the wrong guess.

**Comment by gugavaro** [comment]
those are my cygwin packages:
https://raw.githubusercontent.com/project-everest/everest/master/cygwin-packages

and those are my opam packages:
https://raw.githubusercontent.com/project-everest/everest/master/opam-packages

**Comment by fdopen** [comment]
It should now work as expected.  It's perhaps a problem with your CI setup/manual installation. Uninstall `mingw64-x86_64-pkg-config/mingw64-i686-pkg-config` or make sure that they are not installed in the first place.

**Comment by gugavaro** [comment]
I am not installing those packages anymore (see https://raw.githubusercontent.com/project-everest/everest/master/cygwin-packages) and still getting the conflict.

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[depext: make] Command started
∗  installed depext.1.0.5
Done.

=-=- Carrying on to "C:\cygwin64\usr\local\bin\opam.exe depext ppx_deriving ppx_deriving_yojson zarith pprint wasm process fileutils stdint batteries sqlite3 menhir fix sedlex ctypes ulex visitors ctypes-foreign ocaml-migrate-parsetree hex ppx_tools_versioned.5.2" 

# Detecting depexts using flags: x86_64 mswindows win32 cygwinports
# The following system packages are needed:
#  - gmp
#  - libffi
#  - pkg-config
#  - sqlite3
#  - system:time
installed:gmp
installed:libffi
installed:sqlite3
installed:system:time
# The following new OS packages need to be installed: pkg-config
Starting cygwin install, version 2.895
User has backup/restore rights
Current Directory: C:\cygwin64\packages
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: C:\cygwin64 system
Selected local directory: C:\cygwin64\packages
net: Preconfig
site: http://cygwin.mirror.constant.com/
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst.sig
HTTP status 404 fetching http://cygwin.mirror.constant.com/x86_64/setup.zst
solving: 1 tasks, update: no, use test packages: no
Problem 1/1
installed package pkg-config-1.6.0-1 obsoletes mingw64-x86_64-pkg-config provided by mingw64-x86_64-pkg-config-1.6.0-1
Solution 1/2
  - allow replacement of pkg-config-1.6.0-1 with pkg-config-0.29.1-1
Solution 2/2 (default)
  - do not ask to install mingw64-x86_64-pkg-config-1.6.0-1

Augmented Transaction List: is empty
Changing gid back to original
running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"
running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_man-db.sh"
Changing gid to Administrators
Ending cygwin install
installation failed‌
```



My logs show that pkg-config-1.6.0-1 is installed by mingw64-i686-openssl

Installing the following packages:
mingw64-i686-openssl
By installing you accept licenses for the packages.
 [Cygwin] Starting cygwin install, version 2.895
 [Cygwin] User has backup/restore rights
 [Cygwin] Current Directory: C:\cygwin64\packages
 [Cygwin] Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
 [Cygwin] root: C:\cygwin64 system
 [Cygwin] Selected local directory: C:\cygwin64\packages
 [Cygwin] net: Preconfig
 [Cygwin] site: http://mirrors.kernel.org/sourceware/cygwin/
 [Cygwin] HTTP status 404 fetching http://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.zst.sig
 [Cygwin] HTTP status 404 fetching http://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.zst
 [Cygwin] solving: 1 tasks, update: no, use test packages: no
 [Cygwin] Augmented Transaction List:
 [Cygwin]    0 install                                     libpkgconf3             1.6.0-1
 [Cygwin]    1 install                                         pkgconf             1.6.0-1
 [Cygwin]    2 install                                      pkg-config             1.6.0-1
 [Cygwin]    3 install                               mingw64-i686-zlib            1.2.11-1
 [Cygwin]    4 install                            mingw64-i686-openssl            1.0.2o-1
 [Cygwin] Downloaded C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/libpkgconf3/libpkgconf3-1.6.0-1.tar.xz
 [Cygwin] Downloaded C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/pkgconf-1.6.0-1.tar.xz
 [Cygwin] Downloaded C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/pkg-config/pkg-config-1.6.0-1.tar.xz
 [Cygwin] Downloaded C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/noarch/release/mingw64-i686-zlib/mingw64-i686-zlib-1.2.11-1.tar.xz
 [Cygwin] Downloaded C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/noarch/release/mingw64-i686-openssl/mingw64-i686-openssl-1.0.2o-1.tar.xz
 [Cygwin] Extracting from file://C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/libpkgconf3/libpkgconf3-1.6.0-1.tar.xz
 libpkgconf3-1.6.0-1 has been installed successfully.
 [Cygwin] Extracting from file://C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/pkgconf-1.6.0-1.tar.xz
 pkgconf-1.6.0-1 has been installed successfully.
 [Cygwin] Extracting from file://C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/x86_64/release/pkgconf/pkg-config/pkg-config-1.6.0-1.tar.xz
 pkg-config-1.6.0-1 has been installed successfully.
 [Cygwin] Extracting from file://C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/noarch/release/mingw64-i686-zlib/mingw64-i686-zlib-1.2.11-1.tar.xz
 mingw64-i686-zlib-1.2.11-1 has been installed successfully.
 [Cygwin] Extracting from file://C:\cygwin64\packages/http%3a%2f%2fmirrors.kernel.org%2fsourceware%2fcygwin%2f/noarch/release/mingw64-i686-openssl/mingw64-i686-openssl-1.0.2o-1.tar.xz
 mingw64-i686-openssl-1.0.2o-1 has been installed successfully.
 [Cygwin] Changing gid back to original
 [Cygwin] running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
 [Cygwin] running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"
 [Cygwin] running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_man-db.sh"
 [Cygwin] Changing gid to Administrators
 [Cygwin] Ending cygwin install

Installed:
 - pkgconf-1.6.0-1 v
 - pkg-config-1.6.0-1 v
 - mingw64-i686-openssl-1.0.2o-1 v
 - libpkgconf3-1.6.0-1 v
 - mingw64-i686-zlib-1.2.11-1 v

**Comment by fdopen** [comment]
You are still using opam version 1.x. The repo for this version is not longer mantained.
I've now pushed this specific fix to this repo, too; but you should update your scripts and use opam 2.X nevertheless.

**Comment by gugavaro** [comment]
Thanks @fdopen  
It works now :)
